version: "3.9"

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/wagtail/web/staticfiles
      - media_volume:/home/wagtail/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn songbird.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/wagtail/web/staticfiles
      - media_volume:/home/wagtail/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DB
    env_file:
      - ./.env
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    expose:
      - 6379
volumes:
  postgres_data:
  static_volume:
  media_volume:
